/**
 * en.ts — English UI strings for Velvet Shadow
 *
 * Mirror of tr.ts with native-quality English translations.
 * Structure must stay identical to tr.ts so the Translations type
 * (defined in i18n.ts) keeps both files in lockstep at compile time.
 *
 * @author AKBOYS Team
 * @since 2026-05-13
 */

import type { Translations } from './i18n';

export const T: Translations = {
  app: {
    title: 'The Velvet Shadow',
    subtitle: 'A multiplayer AI mystery game',
    tagline: '2–10 players, a new story every time',
  },

  home: {
    createTitle: 'Create a New Room',
    createHint: 'Start the story yourself and send your friends the code',
    createButton: 'Create Room',
    creating: 'Creating…',
    joinTitle: 'Join a Room',
    joinHint: 'Enter the 6-character room code',
    joinPlaceholder: 'ABC123',
    joinButton: 'Join',
    joining: 'Joining…',
    spectatorJoin: '👁 Join as spectator',
    signOut: 'Sign Out',
    courseNote: 'The Velvet Shadow',
  },

  multiplayer: {
    noRoom: 'No room was found with that code',
    invalidCode: 'Please enter a valid 6-character code',
  },

  lobby: {
    roomCodeLabel: 'Room Code',
    waitingForPlayers: 'Waiting for players…',
    waitingForHost: 'The host is preparing the story…',
    playersTitle: 'Players',
    youLabel: '(you)',
    hostLabel: '(host)',
    promptTitle: 'What Kind of Story Do You Want?',
    promptSubtitle: 'Write a theme or pick one of the suggestions below. The AI will build the world for you.',
    promptPlaceholder: 'Example: A missing jazz singer in 1927 Chicago…',
    promptSurprise: 'Surprise me',
    presets: [
      '1927 Chicago — A singer vanishes from the Velvet Lounge',
      'Antarctic research station — A scientist has disappeared',
      'International Space Station — A killer among the crew',
      'A medieval castle — The king was poisoned at the banquet',
    ],
    createStory: 'Create the Story',
    generating: 'Writing the story…',
    preparing: 'Preparing…',
    openCurtain: 'Raise the Curtain',
    storyReady: 'The story is ready. The curtain rises.',
    audioPreparing: 'Audio is loading...',
    shareLink: 'Copy Invite Link',
  },

  opening: {
    skip: 'Skip',
    continue: 'Continue',
    start: 'Begin the Story',
    loading: 'Preparing the scene…',
    imageLoading: 'Loading the visual…',
  },

  game: {
    openingDivider: '── Opening ──',
    closeAria: 'Close',
    turnsRemaining: 'turns left',
    moveActionPrefix: 'I head to the ',
    moveActionSuffix: '.',
    turnsLabel: 'Turn',
    mapLabel: 'Map',
    commLabel: 'Comms',
    leave: 'Leave',
    accuse: 'Accuse',
    invite: 'Invite',
    copied: 'Copied!',
    mapToggle: 'Map',
    sendPlaceholder: 'What do you do?',
    sendPlaceholderNamed: 'What do you do, {name}?',
    send: 'Send',
    fallbackLookAround: 'Look around',
    fallbackExamineRoom: 'Examine the room',
    fallbackMoveOn: 'Move on',
    playersHeading: 'Players',
    youSuffix: 'you',
    statusOnline: 'Online',
    statusOffline: 'Offline',
    systemJoined: ' joined the session.',
    systemReconnected: ' reconnected.',
    systemDisconnected: ' disconnected.',
    narratorWriting: 'The narrator is writing…',
    narratorWritingToYouPrefix: 'The narrator is writing to ',
    narratorWritingToYouSubject: 'you',
    narratorWritingToYouSuffix: '…',
    narratorWritingToOtherPrefix: 'The narrator is writing to ',
    narratorWritingToOtherSuffix: '…',
    narratorLabel: 'Narrator',
    playerLabel: 'Player',
    queueLabel: 'Queue:',
    waitingForOthers: 'Waiting for the other players to respond…',
    typing: 'typing',
    /* Locale-aware extras (#58 follow-up) */
    confirmLeave: 'Are you sure you want to leave?',
    loadingSession: 'Loading session…',
    sessionNotFound: 'Session not found',
    backToHome: 'Back to Home',
    connectingToServer: 'Connecting to server…',
    joiningAs: 'Joining as {name}…',
    nameTaken: 'Name already taken, please choose another',
    reconnecting: 'Reconnecting…',
    narratorContemplates: 'The narrator contemplates…',
    isTypingSingle: '{name} is typing…',
    isTypingMultiple: '{names} are typing…',
    observedLabel: 'Observed',
    imageLoading: 'Visualizing scene…',
    youCommLabel: 'You',
    spectatorBadge: '👁 Spectator',
    spectatorFooter: '👁 Spectator mode — read only',
    queueYouBadge: 'YOU',
    chatInputBlocked: 'The narrator is replying…',
    /* Mobile voice push-to-talk button (#mobile) */
    voiceButtonHoldToTalk: 'Hold to talk',
    voiceButtonHoldShort: 'HOLD',
    voiceButtonOn: 'LIVE',
    voiceButtonDisabled: 'MIC',
  },

  minimap: {
    title: 'Map',
    youAreHere: 'You are here',
    unknownRoom: 'Unknown room',
    visited: 'Visited',
    unvisited: 'Not visited yet',
    /* GameMap modal (#mobile-i18n) */
    discovered: 'Discovered',
    mapNotAvailable: 'Map not available.',
    legendYou: 'You',
    legendVisited: 'Visited',
    legendUnknown: 'Unknown',
    travelHint: 'Click an adjacent node to travel',
    teamHeader: 'TEAM',
    teamCount: '{n} Detectives',
    youSuffix: '(you)',
    locationUnknown: 'Unknown',
    teammateLocationHint: "Teammate locations only visible in rooms you've explored.",
    /* Theme titles + subtitles (already English; kept here so the same
     * lookup key works for both locales) */
    themeTitleNoir: 'Case Evidence Board',
    themeSubtitleNoir: 'Classified — Chicago P.D.',
    themeTitleHaunted: 'The Manor Floor Plan',
    themeSubtitleHaunted: 'Surveyed MCMLXXVII',
    themeTitleSpace: 'Station Zero // Schematic',
    themeSubtitleSpace: 'SEC-01 / DECK-A / REV 7.2',
    themeTitlePirate: 'The Crimson Tide — Chart',
    themeSubtitlePirate: 'Aye, X Marks the Spot',
    themeTitleWestern: 'Dust & Ashes — Town Plan',
    themeSubtitleWestern: 'Frontier Survey, Eighteen-Seventy',
    themeTitleCyberpunk: 'NEON GHOSTS // GRID-07',
    themeSubtitleCyberpunk: '// 2087.04.08 :: SCTR-7 :: ACTIVE',
  },

  comm: {
    title: 'Comms',
    roomTab: 'This Room',
    directTab: 'Direct',
    placeholder: 'Type a message…',
    noMessages: 'No messages yet',
  },

  evidence: {
    title: 'Evidence Board',
    subtitle: "The team's shared notes",
    placeholder: 'Share evidence or a thought…',
    noMessages: 'No notes yet. Be the first to share something.',
    send: 'Post',
  },

  voice: {
    section: 'Voice Chat',
    hotkeyHint: 'Hold V to speak.',
    input: 'Microphone',
    output: 'Speaker',
    systemDefault: 'System default',
    ready: 'Ready',
    connecting: 'Connecting…',
    denied: 'Permission denied',
    unsupported: 'Not supported',
  },

  tutorial: {
    title: 'Quick Tour',
    stepOf: 'Step {n} of {total}',
    next: 'Next',
    prev: 'Back',
    skip: 'Skip',
    finish: 'Done',
    replayButton: 'Replay the Tour',
    steps: {
      turn: {
        title: 'Turn Counter',
        body: 'Track your remaining turns here. As the bar shifts from green to red, time is running out.',
      },
      chat: {
        title: 'Narrator & Chat',
        body: "The story unfolds here. The opening narration is at the top; your and your team's actions follow below.",
      },
      input: {
        title: 'Your Action',
        body: 'Type what you want to do here. Keep it short and clear: "Open the door", "Talk to the bartender".',
      },
      accuse: {
        title: 'Accusation',
        body: 'If you think you have found the killer, start an accusation here. Your team decides by unanimous vote.',
      },
      settings: {
        title: 'Audio & Settings',
        body: 'Music, sound effects, and voice chat (push-to-talk with V) live here. You can replay the tour from this menu.',
      },
    },
  },

  accuse: {
    title: 'Propose an Accusation',
    subtitle: 'Who do you think did it, and with what evidence?',
    suspect: 'Suspect',
    evidence: 'Key Evidence',
    cancel: 'Cancel',
    propose: 'Propose Accusation',
    youAccused: 'is calling for a verdict',
    voteTitle: 'Team Verdict',
    voteQuestion: 'Do you agree?',
    voteYes: 'Yes, they did it',
    voteNo: 'No, it was not them',
    voted: 'You have cast your vote',
    waitingForTeam: 'Waiting for the other players to vote…',
    unanimousRequired: 'A unanimous vote is required — a single "no" keeps the case open.',
    timeLeft: 'seconds left',
    noSuspectsYet: "You haven't met anyone yet.",
    proposedPrefix: '',
    proposedMiddle: ' proposed accusing ',
    proposedSuffix: '. All players must vote.',
    bannerLabel: 'Accusation Vote',
    bannerAccusesMiddle: ' accuses ',
    bannerAccusesEnd: '.',
    bannerWaitingForTeam: ' Waiting for your teammates to vote.',
    bannerCastVote: ' Cast your vote.',
    bannerYouVoted: 'You voted:',
    bannerWaitingForOthers: ' — waiting for others.',
    bannerGuilty: 'GUILTY',
    bannerNotGuilty: 'NOT GUILTY',
    bannerSecondsSuffix: 's',
    voteResultGuilty: 'Verdict: GUILTY.',
    voteResultNotGuilty: 'Verdict: NOT GUILTY.',
    voteResultUndecided: "The team couldn't agree. The investigation continues.",
    voteSuffixCorrect: ' — The team was right.',
    voteSuffixWrong: ' — The team was wrong.',
    result: {
      won: 'Case Solved',
      lost_wrong: 'Case Lost',
      lost_timeout: 'The Trail Went Cold',
    },
  },

  finale: {
    connecting: 'Cueing the finale music…',
    loading: 'Writing the ending of the story…',
    home: 'Back to Home',
    playAgain: 'Play Again',
    revealTitle: 'What Really Happened',
    foundLabel: 'Evidence Found',
    missedLabel: 'Evidence Missed',
    timeline: "The Team's Journey",
    trueCulprit: 'The True Culprit',
  },

  login: {
    title: 'Sign In',
    google: 'Sign in with Google',
    privacy: 'Your sign-in is used only for game sessions.',
  },

  name: {
    title: 'Who are you, detective?',
    subtitle: 'Tell your teammates how to recognize you.',
    placeholder: 'Type your name…',
    save: 'Save',
    change: 'Change Name',
  },

  errors: {
    generic: 'Something went wrong',
    sessionNotFound: 'Session not found',
    generating: 'Could not create the story',
    voteError: 'Could not register your vote',
    networkError: 'Connection problem',
  },

  ambient: {
    musicOn: 'Music on',
    musicOff: 'Music off',
  },

  audio: {
    settings: 'Audio Settings',
    ambient: 'Ambient Music',
    sfx: 'Sound Effects',
    mute: 'Mute',
    unmute: 'Unmute',
    open: 'Open audio settings',
    close: 'Close',
  },

  locale: {
    sectionTitle: 'Language',
    sectionHint: 'Language cannot be changed once the game has started.',
    locked: 'Language is locked after the game starts',
    turkish: 'Türkçe',
    english: 'English',
    onboardingTitle: 'Your Language?',
    onboardingSubtitle: 'Pick the language you want to play in. You can change it later from the home screen or settings.',
    onboardingHint: 'Players in the same game can pick different languages — everyone reads the same story in their own.',
  },

  caseFile: {
    download: 'Download Case File',
    preparing: 'Preparing PDF…',
    failed: 'Could not generate the PDF, please retry',
    retry: 'Try Again',
  },

  reconstruction: {
    cta: 'Reconstruct the Crime Scene',
    loading: 'Piecing together what really happened…',
    failed: 'Could not reconstruct the chain of events.',
    retry: 'Try Again',
    title: 'What Really Happened',
    culpritBadge: "The killer's move",
    autoplay: 'Autoplay',
    pause: 'Pause',
    next: 'Next',
    prev: 'Previous',
    close: 'Close',
    eventOf: 'Event {n} of {total}',
    conclusionTitle: 'Conclusion',
  },

  replay: {
    title: 'Game Replay',
    loadingReplay: 'Loading replay…',
    home: 'Home',
    systemLabel: 'System',
    playersTitle: 'Players',
    infoTitle: 'Game Info',
    totalTurns: 'Total turns',
    messageCount: 'Message count',
    playedOn: 'Played on',
    revealTitle: 'What Really Happened',
    showTimeline: 'Show Event Chain',
    conclusionTitle: 'Conclusion',
    play: '▶ Play',
    pause: '⏸ Pause',
    restart: '↩ Restart',
    fromStart: '↩ From Start',
    firstMessage: 'Message 1',
    lastMessageOf: 'Message {total}',
    progress: '{n} / {total}',
  },
};
