/**
 * tr.ts — Turkish UI strings for Velvet Shadow
 *
 * Single source of Turkish labels. Keep flat and explicit so components
 * can import exactly what they need without dynamic key lookups.
 *
 * @author AKBOYS Team
 * @since 2026-04-17
 */

export const T = {
  app: {
    title: 'The Velvet Shadow',
    subtitle: 'Çok oyunculu AI hikâye oyunu',
    tagline: '2–10 oyuncu, her seferinde yeni bir hikâye',
  },

  home: {
    createTitle: 'Yeni Oda Aç',
    createHint: 'Hikâyeyi sen başlat, arkadaşlarına kodu gönder',
    createButton: 'Oda Oluştur',
    creating: 'Oluşturuluyor…',
    joinTitle: 'Bir Odaya Katıl',
    joinHint: '6 haneli oda kodunu gir',
    joinPlaceholder: 'ABC123',
    joinButton: 'Katıl',
    joining: 'Katılıyor…',
    spectatorJoin: '👁 İzleyici olarak katıl',
    signOut: 'Çıkış Yap',
    courseNote: 'COMP 491 · AKBOYS · Bahar 2026',
  },

  multiplayer: {
    noRoom: 'Bu kod ile bir oda bulunamadı',
    invalidCode: 'Lütfen geçerli bir 6 haneli kod yaz',
  },

  lobby: {
    roomCodeLabel: 'Oda Kodu',
    waitingForPlayers: 'Oyuncular bekleniyor…',
    waitingForHost: 'Host hikayeyi hazırlıyor…',
    playersTitle: 'Oyuncular',
    youLabel: '(sen)',
    hostLabel: '(host)',
    promptTitle: 'Nasıl Bir Hikaye İstersin?',
    promptSubtitle: 'Bir tema yaz ya da aşağıdaki önerilerden birini seç. AI dünyayı senin için yaratacak.',
    promptPlaceholder: 'Örnek: 1927 Chicago\'da kayıp bir caz şarkıcısı…',
    promptSurprise: 'Sürpriz olsun',
    presets: [
      '1927 Chicago — Velvet Lounge\'da kayıp bir şarkıcı',
      'Antarktika araştırma üssü — Bir bilim insanı ortadan kayboldu',
      'Uluslararası Uzay İstasyonu — Mürettebat arasında bir katil var',
      'Ortaçağ kalesi — Kral ziyafette zehirlendi',
    ],
    createStory: 'Hikayeyi Oluştur',
    generating: 'Hikaye yazılıyor…',
    preparing: 'Hazırlanıyor…',
    openCurtain: 'Perdeyi Aç',
    storyReady: 'Hikaye hazır. Perde açılıyor.',
    audioPreparing: 'Ses hazırlanıyor...',
    shareLink: 'Bağlantıyı Kopyala',
  },

  opening: {
    skip: 'Geç',
    continue: 'Devam Et',
    start: 'Hikayeye Başla',
    loading: 'Sahne hazırlanıyor…',
    imageLoading: 'Görsel hazırlanıyor…',
  },

  game: {
    openingDivider: '── Açılış ──',
    closeAria: 'Kapat',
    turnsRemaining: 'tur kaldı',
    moveActionPrefix: '',
    moveActionSuffix: ' odasına gidiyorum.',
    turnsLabel: 'Tur',
    mapLabel: 'Harita',
    commLabel: 'Telsiz',
    leave: 'Ayrıl',
    accuse: 'Suçla',
    invite: 'Davet',
    copied: 'Kopyalandı!',
    mapToggle: 'Harita',
    sendPlaceholder: 'Ne yapıyorsun?',
    sendPlaceholderNamed: 'Ne yapıyorsun, {name}?',
    send: 'Gönder',
    fallbackLookAround: 'Etrafına bak',
    fallbackExamineRoom: 'Odayı incele',
    fallbackMoveOn: 'İleri git',
    playersHeading: 'Oyuncular',
    youSuffix: 'sen',
    statusOnline: 'Çevrimiçi',
    statusOffline: 'Çevrimdışı',
    systemJoined: ' oyuna katıldı.',
    systemReconnected: ' yeniden bağlandı.',
    systemDisconnected: ' bağlantısı koptu.',
    narratorWriting: 'Anlatıcı yazıyor…',
    narratorWritingToYouPrefix: 'Anlatıcı ',
    narratorWritingToYouSubject: 'sana',
    narratorWritingToYouSuffix: ' yazıyor…',
    narratorWritingToOtherPrefix: 'Anlatıcı ',
    narratorWritingToOtherSuffix: '\'e yazıyor…',
    narratorLabel: 'Anlatıcı',
    playerLabel: 'Oyuncu',
    queueLabel: 'Sırada:',
    waitingForOthers: 'Diğer oyuncuların cevap vermesi bekleniyor…',
    typing: 'yazıyor',
    /* Locale-aware extras (#58 follow-up) */
    confirmLeave: 'Ayrılmak istediğinden emin misin?',
    loadingSession: 'Oturum yükleniyor…',
    sessionNotFound: 'Oturum bulunamadı',
    backToHome: 'Ana Sayfaya Dön',
    connectingToServer: 'Sunucuya bağlanılıyor…',
    joiningAs: '{name} olarak katılıyor…',
    nameTaken: 'Bu isim alınmış, lütfen başka bir isim seç',
    reconnecting: 'Yeniden bağlanıyor…',
    narratorContemplates: 'Anlatıcı düşünüyor…',
    isTypingSingle: '{name} yazıyor…',
    isTypingMultiple: '{names} yazıyor…',
    observedLabel: 'Gözlem',
    imageLoading: 'Sahne görselleştiriliyor…',
    youCommLabel: 'Sen',
    spectatorBadge: '👁 İzleyici',
    spectatorFooter: '👁 İzleyici modunda — sadece okuyabilirsiniz',
    queueYouBadge: 'SEN',
    chatInputBlocked: 'Anlatıcı yanıtlıyor…',
  },

  minimap: {
    title: 'Harita',
    youAreHere: 'Buradasın',
    unknownRoom: 'Bilinmeyen oda',
    visited: 'Ziyaret edildi',
    unvisited: 'Henüz gidilmedi',
  },

  comm: {
    title: 'Telsiz',
    roomTab: 'Bu Oda',
    directTab: 'Direkt',
    placeholder: 'Mesaj yaz…',
    noMessages: 'Henüz bir mesaj yok',
  },

  evidence: {
    title: 'Kanıt Tahtası',
    subtitle: 'Takımın paylaşılan notları',
    placeholder: 'Bir kanıt veya düşünce paylaş…',
    noMessages: 'Henüz bir not yok. İlk düşünceyi sen paylaş.',
    send: 'Gönder',
  },

  voice: {
    section: 'Sesli Sohbet',
    hotkeyHint: 'Konuşmak için V tuşunu basılı tut.',
    input: 'Mikrofon',
    output: 'Hoparlör',
    systemDefault: 'Sistem varsayılanı',
    ready: 'Hazır',
    connecting: 'Bağlanıyor…',
    denied: 'İzin yok',
    unsupported: 'Desteklenmiyor',
  },

  tutorial: {
    title: 'Hızlı Tur',
    stepOf: 'Adım {n} / {total}',
    next: 'İleri',
    prev: 'Geri',
    skip: 'Atla',
    finish: 'Bitir',
    replayButton: 'Tanıtımı Tekrar Göster',
    steps: {
      turn: {
        title: 'Tur Sayacı',
        body: 'Kalan tur sayını buradan takip et. Yeşilden kırmızıya geçtikçe zamanın azalıyor demektir.',
      },
      chat: {
        title: 'Anlatıcı & Sohbet',
        body: 'Hikaye buradan akıyor. Açılış metni en üstte; senin ve takımın aksiyonları sonra geliyor.',
      },
      input: {
        title: 'Aksiyonun',
        body: 'Ne yapmak istediğini buraya yaz. Kısa ve net olsun: "Kapıyı aç", "Barmenle konuş" gibi.',
      },
      accuse: {
        title: 'Suçlama',
        body: 'Katili bulduğunu düşünüyorsan buradan suçlama başlat. Takımın oybirliğiyle karar verir.',
      },
      settings: {
        title: 'Ses & Ayarlar',
        body: 'Müzik, ses efektleri ve sesli sohbet (V tuşuyla konuşma) ayarları burada. Tanıtımı buradan tekrar açabilirsin.',
      },
    },
  },

  accuse: {
    title: 'Suçlama Öner',
    subtitle: 'Kimin yaptığını düşünüyorsun ve hangi kanıtla?',
    suspect: 'Şüpheli',
    evidence: 'Anahtar Kanıt',
    cancel: 'Vazgeç',
    propose: 'Suçlamayı Öner',
    youAccused: 'takıma sesleniyor',
    voteTitle: 'Takım Kararı',
    voteQuestion: 'Hemfikir misin?',
    voteYes: 'Evet, o yaptı',
    voteNo: 'Hayır, o değil',
    voted: 'Oyunu kullandın',
    waitingForTeam: 'Diğer oyuncuların oyu bekleniyor…',
    unanimousRequired: 'Oybirliği gerekli — biri bile hayır derse dava kapanmaz.',
    timeLeft: 'kalan saniye',
    noSuspectsYet: 'Henüz kimseyle karşılaşmadın.',
    proposedPrefix: '',
    proposedMiddle: ' suçlamayı önerdi: ',
    proposedSuffix: '. Tüm oyuncular oy kullanmalı.',
    bannerLabel: 'Suçlama Oylaması',
    bannerAccusesMiddle: ' suçluyor: ',
    bannerAccusesEnd: '.',
    bannerWaitingForTeam: ' Takım arkadaşlarının oyunu bekle.',
    bannerCastVote: ' Oyunu kullan.',
    bannerYouVoted: 'Oy kullandın:',
    bannerWaitingForOthers: ' — diğerleri bekleniyor.',
    bannerGuilty: 'SUÇLU',
    bannerNotGuilty: 'SUÇSUZ',
    bannerSecondsSuffix: 's',
    voteResultGuilty: 'Karar: SUÇLU.',
    voteResultNotGuilty: 'Karar: SUÇSUZ.',
    voteResultUndecided: 'Takım hemfikir olamadı. Soruşturma devam ediyor.',
    voteSuffixCorrect: ' — Takım doğru karar verdi.',
    voteSuffixWrong: ' — Takım yanlış karar verdi.',
    result: {
      won: 'Dava Çözüldü',
      lost_wrong: 'Dava Kaybedildi',
      lost_timeout: 'İzler Soğudu',
    },
  },

  finale: {
    connecting: 'Finalin müziği hazırlanıyor…',
    loading: 'Hikaye bitirişini yazıyor…',
    home: 'Ana Sayfaya Dön',
    playAgain: 'Tekrar Oyna',
    revealTitle: 'Gerçekte Ne Oldu',
    foundLabel: 'Bulunan Kanıtlar',
    missedLabel: 'Kaçırılan Kanıtlar',
    timeline: 'Takımın Yolculuğu',
    trueCulprit: 'Gerçek Katil',
  },

  login: {
    title: 'Giriş Yap',
    google: 'Google ile Giriş Yap',
    privacy: 'Girişin yalnızca oyun oturumları için kullanılır.',
  },

  name: {
    title: 'Kimsin, dedektif?',
    subtitle: 'Takım arkadaşlarının seni nasıl tanıyacağını yaz.',
    placeholder: 'Adını yaz…',
    save: 'Kaydet',
    change: 'İsmini Değiştir',
  },

  errors: {
    generic: 'Bir şeyler ters gitti',
    sessionNotFound: 'Oturum bulunamadı',
    generating: 'Hikaye oluşturulamadı',
    voteError: 'Oy verilemedi',
    networkError: 'Bağlantı sorunu',
  },

  ambient: {
    musicOn: 'Müzik açık',
    musicOff: 'Müzik kapalı',
  },

  audio: {
    settings: 'Ses Ayarları',
    ambient: 'Atmosfer Müziği',
    sfx: 'Ses Efektleri',
    mute: 'Sustur',
    unmute: 'Aç',
    open: 'Ses ayarları',
    close: 'Kapat',
  },

  locale: {
    sectionTitle: 'Dil',
    sectionHint: 'Oyun başladıktan sonra dil değiştirilemez.',
    locked: 'Oyun başladıktan sonra dil değiştirilemez',
    turkish: 'Türkçe',
    english: 'English',
    onboardingTitle: 'Diliniz?',
    onboardingSubtitle: 'Hangi dilde oynamak istediğinizi seçin. Sonradan ana ekran veya ayarlardan değiştirebilirsiniz.',
    onboardingHint: 'Aynı oyunda farklı dilde oynayan oyuncular olabilir — herkes aynı hikayeyi kendi dilinde okur.',
  },

  caseFile: {
    download: 'Vaka Dosyasını İndir',
    preparing: 'PDF hazırlanıyor…',
    failed: 'PDF oluşturulamadı, tekrar dene',
    retry: 'Tekrar Dene',
  },

  reconstruction: {
    cta: 'Olay Yerini Yeniden Canlandır',
    loading: 'Gerçek olaylar bir araya getiriliyor…',
    failed: 'Olay zinciri çıkarılamadı.',
    retry: 'Tekrar Dene',
    title: 'Gerçekte Ne Oldu',
    culpritBadge: 'Katilin hareketi',
    autoplay: 'Otomatik Oynat',
    pause: 'Duraklat',
    next: 'Sonraki',
    prev: 'Önceki',
    close: 'Kapat',
    eventOf: 'Olay {n} / {total}',
    conclusionTitle: 'Sonuç',
  },

  replay: {
    title: 'Oyun Tekrarı',
    loadingReplay: 'Tekrar yükleniyor…',
    home: 'Ana Sayfa',
    systemLabel: 'Sistem',
    playersTitle: 'Oyuncular',
    infoTitle: 'Oyun Bilgisi',
    totalTurns: 'Toplam tur',
    messageCount: 'Mesaj sayısı',
    playedOn: 'Oynandı',
    revealTitle: 'Gerçekte Ne Oldu',
    showTimeline: 'Olay Zincirini Göster',
    conclusionTitle: 'Sonuç',
    play: '▶ Oynat',
    pause: '⏸ Duraklat',
    restart: '↩ Başa Dön',
    fromStart: '↩ Baştan',
    firstMessage: 'Mesaj 1',
    lastMessageOf: 'Mesaj {total}',
    progress: '{n} / {total}',
  },
} as const;
